services:
  app:
    environment:
      - REDIS_DATA_DIR=
    build:
      context: ./
      dockerfile: Dockerfile
    image: 0xjustuzair/redis-go
    ports:
      - "6379:6379"
    restart: unless-stopped
