apiVersion: v1
kind: Service
metadata:
  name: redis-go # Must match the 'serviceName' in the StatefulSet
spec:
  clusterIP: None # This is what makes it "Headless"
  selector:
    app: redis-go
  ports:
    - port: 6379
      targetPort: 6379
